"use client";

import Image from "next/image";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { DashboardData, Donation, DonationInput } from "@/lib/types";

const emptyForm: DonationInput = { batchNumber: "", batchName: "", cashAmount: 0, transferAmount: 0, note: "" };
const money = new Intl.NumberFormat("th-TH", { style: "currency", currency: "THB", minimumFractionDigits: 2 });
const date = new Intl.DateTimeFormat("th-TH", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Bangkok" });
type Toast = { text: string; type: "success" | "error" } | null;

export default function Home() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [revision, setRevision] = useState("");
  const [isAdmin, setIsAdmin] = useState(false);
  const [publicView, setPublicView] = useState(false);
  const [tab, setTab] = useState<"record" | "stats">("record");
  const [loginOpen, setLoginOpen] = useState(false);
  const [login, setLogin] = useState({ username: "", password: "" });
  const [form, setForm] = useState<DonationInput>(emptyForm);
  const [editing, setEditing] = useState<Donation | null>(null);
  const [removing, setRemoving] = useState<Donation | null>(null);
  const [busy, setBusy] = useState(false);
  const [query, setQuery] = useState("");
  const [toast, setToast] = useState<Toast>(null);
  const [celebration, setCelebration] = useState(false);
  const [amountChange, setAmountChange] = useState<number | null>(null);
  const previousTotal = useRef<number | null>(null);
  const notify = useCallback((text: string, type: "success" | "error" = "success") => { setToast({ text, type }); window.setTimeout(() => setToast(null), 3200); }, []);
  const load = useCallback(async () => { try { const r = await fetch("/api/donations", { cache: "no-store" }); if (!r.ok) throw new Error(); const payload = await r.json() as DashboardData; if (previousTotal.current !== null && payload.totalAmount !== previousTotal.current) { const difference = payload.totalAmount - previousTotal.current; setAmountChange(difference); window.setTimeout(() => setAmountChange(null), 4500); if (difference > 0) { setCelebration(true); window.setTimeout(() => setCelebration(false), 10000); } } previousTotal.current = payload.totalAmount; setData(payload); setRevision(payload.revision); } catch { notify("ไม่สามารถโหลดข้อมูลได้", "error"); } }, [notify]);
  const checkForChanges = useCallback(async () => { try { const r = await fetch("/api/donations/changes", { cache: "no-store" }); if (!r.ok) return; const payload = await r.json() as { revision: string }; if (revision && payload.revision !== revision) await load(); } catch { /* Background checks fail silently. */ } }, [load, revision]);
  const getSession = useCallback(async () => { try { setIsAdmin(Boolean((await (await fetch("/api/auth/session")).json()).authenticated)); } catch { setIsAdmin(false); } }, []);
  useEffect(() => { const id = window.setTimeout(() => { void load(); void getSession(); }, 0); return () => clearTimeout(id); }, [load, getSession]);
  useEffect(() => { const id = window.setTimeout(() => setPublicView(new URLSearchParams(window.location.search).get("view") === "public"), 0); return () => window.clearTimeout(id); }, []);
  useEffect(() => {
    if (isAdmin && !publicView) return;
    const interval = window.setInterval(() => void checkForChanges(), 5000);
    return () => window.clearInterval(interval);
  }, [isAdmin, publicView, checkForChanges]);
  const rows = useMemo(() => (data?.donations ?? []).filter((x) => `${x.batchNumber} ${x.batchName} ${x.note}`.toLowerCase().includes(query.toLowerCase())), [data, query]);
  const update = (key: keyof DonationInput, value: string) => setForm((f) => ({ ...f, [key]: key === "cashAmount" || key === "transferAmount" ? Number(value) : value }));
  const edit = (d: Donation) => { setEditing(d); setForm({ batchNumber: d.batchNumber, batchName: d.batchName, cashAmount: d.cashAmount, transferAmount: d.transferAmount, note: d.note }); setTab("record"); };
  const clearEditor = () => { setEditing(null); setForm(emptyForm); };
  async function loginSubmit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); try { const r = await fetch("/api/auth/session", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(login) }); const p = await r.json(); if (!r.ok) throw new Error(p.message); setIsAdmin(true); setLoginOpen(false); setLogin({ username: "", password: "" }); notify("เข้าสู่ระบบผู้ดูแลสำเร็จ"); } catch (error) { notify(error instanceof Error ? error.message : "เข้าสู่ระบบไม่สำเร็จ", "error"); } finally { setBusy(false); } }
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); try { const r = await fetch(editing ? `/api/donations/${editing.id}` : "/api/donations", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const p = await r.json(); if (!r.ok) throw new Error(p.message); notify(editing ? "แก้ไขข้อมูลเรียบร้อย" : "บันทึกรายการเรียบร้อย"); clearEditor(); await load(); } catch (error) { notify(error instanceof Error ? error.message : "บันทึกไม่สำเร็จ", "error"); } finally { setBusy(false); } }
  async function remove() { if (!removing) return; setBusy(true); try { const r = await fetch(`/api/donations/${removing.id}`, { method: "DELETE" }); const p = await r.json(); if (!r.ok) throw new Error(p.message); setRemoving(null); notify("ลบรายการเรียบร้อย"); await load(); } catch (error) { notify(error instanceof Error ? error.message : "ลบไม่สำเร็จ", "error"); } finally { setBusy(false); } }
  async function logout() { await fetch("/api/auth/session", { method: "DELETE" }); setIsAdmin(false); setTab("record"); clearEditor(); notify("ออกจากระบบแล้ว"); }

  return <main className="min-h-screen bg-[#f7f8fa]">{isAdmin && !publicView ? <AdminView data={data} tab={tab} setTab={setTab} form={form} update={update} save={save} editing={editing} clearEditor={clearEditor} busy={busy} rows={rows} query={query} setQuery={setQuery} edit={edit} remove={setRemoving} logout={logout} load={load} /> : isAdmin ? <PublicAdminView data={data} load={load} backToAdmin={() => { window.history.replaceState({}, "", "/"); setPublicView(false); }} /> : <PublicView data={data} openLogin={() => setLoginOpen(true)} load={load} />}
    {loginOpen && <LoginModal login={login} setLogin={setLogin} close={() => setLoginOpen(false)} submit={loginSubmit} busy={busy} />}
    {removing && <DeleteModal donation={removing} cancel={() => setRemoving(null)} confirm={remove} busy={busy} />}
    {toast && <div className={`fixed bottom-5 right-5 z-50 flex items-center gap-3 rounded-2xl px-4 py-3 text-sm font-bold text-white shadow-xl ${toast.type === "success" ? "bg-emerald-600" : "bg-rose-600"}`}><i className={`fa-solid ${toast.type === "success" ? "fa-circle-check" : "fa-circle-exclamation"}`} />{toast.text}<button onClick={() => setToast(null)}><i className="fa-solid fa-xmark" /></button></div>}
    {celebration && (!isAdmin || publicView) && <DonationCelebration />}
    {amountChange !== null && (!isAdmin || publicView) && <TotalChangeEffect amount={amountChange} />}
  </main>;
}

function TotalChangeEffect({ amount }: { amount: number }) {
  return <div className="total-change-effect" aria-hidden="true"><span className="total-change-ring" /><span className="total-change-coin coin-one"><i className="fa-solid fa-coins" /></span><span className="total-change-coin coin-two"><i className="fa-solid fa-baht-sign" /></span><strong>{amount > 0 ? "+" : ""}{money.format(amount)}</strong></div>;
}

function DonationCelebration() {
  const sparks = Array.from({ length: 46 }, (_, index) => ({ x: ((index * 97) % 620) - 310, y: -110 - ((index * 53) % 280), turn: (index * 67) % 720, color: ["#fbbf24", "#fb923c", "#fef3c7", "#34d399", "#ffffff"][index % 5] }));
  const coins = Array.from({ length: 16 }, (_, index) => ({ left: 4 + ((index * 31) % 92), delay: (index % 8) * 90, size: 18 + ((index * 7) % 18) }));
  return <div className="celebration-layer celebration-wow" aria-hidden="true"><div className="celebration-flash" /><div className="celebration-rays" /><div className="firework firework-left"><span /><span /><span /></div><div className="firework firework-right"><span /><span /><span /></div><div className="coin-celebration"><div className="coin-face"><i className="fa-solid fa-baht-sign" /></div></div><div className="celebration-message"><span>ยอดใหม่เข้ามาแล้ว!</span><strong><i className="fa-solid fa-hands-holding-heart" /> ขอบคุณทุกพลังแห่งการให้</strong></div>{sparks.map((spark, index) => <span key={`spark-${index}`} className="celebration-spark" style={{ "--x": `${spark.x}px`, "--y": `${spark.y}px`, "--turn": `${spark.turn}deg`, "--spark": spark.color, animationDelay: `${(index % 9) * 28}ms` } as React.CSSProperties} />)}{coins.map((coin, index) => <i key={`coin-${index}`} className="fa-solid fa-coins coin-rain" style={{ left: `${coin.left}%`, fontSize: `${coin.size}px`, animationDelay: `${coin.delay}ms` } as React.CSSProperties} />)}</div>;
}

function AnimatedMoney({ value }: { value: number }) {
  const [display, setDisplay] = useState(value);
  const previous = useRef(value);
  useEffect(() => {
    const startValue = previous.current;
    const difference = value - startValue;
    const startedAt = performance.now();
    let frame = 0;
    const tick = (now: number) => {
      const progress = Math.min((now - startedAt) / 4500, 1);
      const eased = 1 - Math.pow(1 - progress, 4);
      setDisplay(startValue + difference * eased);
      if (progress < 1) frame = requestAnimationFrame(tick);
    };
    frame = requestAnimationFrame(tick);
    previous.current = value;
    return () => cancelAnimationFrame(frame);
  }, [value]);
  return <span key={value} className="animated-money">{money.format(display)}</span>;
}

function LiveNow() {
  const [time, setTime] = useState("--:--:--");
  useEffect(() => {
    const format = () => new Intl.DateTimeFormat("th-TH", { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false, timeZone: "Asia/Bangkok" }).format(new Date());
    const update = () => setTime(format());
    update();
    const interval = window.setInterval(update, 1000);
    return () => window.clearInterval(interval);
  }, []);
  return <div className="live-now" aria-label={`ข้อมูลสด เวลา ${time}`}><span /><strong>LIVE</strong><time>{time}</time></div>;
}

function Brand({ admin = false }: { admin?: boolean }) {
  const [adminName, setAdminName] = useState("ผู้ดูแลระบบ");
  useEffect(() => {
    if (!admin) return;
    let active = true;
    void fetch("/api/auth/session", { cache: "no-store" }).then((response) => response.json()).then((session) => { if (active && session.user?.displayName) setAdminName(session.user.displayName); });
    return () => { active = false; };
  }, [admin]);
  const content = <><Image src="/img/logo.png" width={54} height={54} alt="ตราโรงเรียนจอมทอง" className="h-11 w-11 rounded-xl bg-white object-contain p-1 shadow-sm" priority /><div><p className="font-extrabold text-slate-900">{admin ? "ศูนย์จัดการผ้าป่า" : "ระบบนับยอดผ้าป่า"}</p><p className="text-xs text-slate-500">{admin ? `ผู้ดูแล: ${adminName}` : "โรงเรียนจอมทอง"}</p></div></>;
  if (!admin) return <div className="flex items-center gap-3">{content}</div>;
  return <button type="button" onClick={() => { window.location.href = "/?view=public"; }} title="กลับไปหน้าหลัก" className="flex items-center gap-3 rounded-xl text-left transition hover:bg-slate-50 hover:pr-3"><>{content}</><span className="hidden rounded-lg bg-orange-50 px-2 py-1 text-xs font-bold text-orange-600 sm:inline"><i className="fa-solid fa-house mr-1" />หน้าหลัก</span></button>;
}
function PublicView({ data, openLogin, load }: { data: DashboardData | null; openLogin: () => void; load: () => Promise<void> }) { return <><header className="sticky top-0 z-20 border-b border-slate-200/80 glass"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6"><Brand /><div className="flex gap-2"><button className="btn btn-soft px-3 text-sm" onClick={() => void load()}><i className="fa-solid fa-rotate-right" /><span className="hidden sm:inline">รีเฟรช</span></button><button className="btn btn-primary px-3 text-sm" onClick={openLogin}><i className="fa-solid fa-lock" /><span className="hidden sm:inline">เข้าสู่ระบบ</span></button></div></div></header><section className="mx-auto max-w-7xl px-4 pt-7 sm:px-6 lg:pt-10"><div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-amber-400 via-orange-500 to-orange-600 px-6 py-9 text-white shadow-xl shadow-orange-200 sm:px-10 sm:py-12"><div className="absolute -right-12 -top-20 h-64 w-64 rounded-full bg-white/15" /><LiveNow /><div className="relative text-center"><p className="text-lg font-bold text-orange-50"><i className="fa-solid fa-hands-holding-circle mr-2" />ยอดผ้าป่ารวมทั้งหมด</p>{data ? <><h1 className="mt-3 text-5xl font-black tracking-tight sm:text-7xl"><AnimatedMoney value={data.totalAmount} /></h1><p className="mt-4 text-sm text-orange-50">เข้ามาแล้ว {data.totalBatches.toLocaleString("th-TH")} รุ่น · {data.totalRecords.toLocaleString("th-TH")} รายการ</p></> : <div className="skeleton mx-auto mt-4 h-16 max-w-sm bg-white/30" />}</div></div></section><section className="mx-auto max-w-7xl px-4 py-7 sm:px-6"><PaymentSummary data={data} /><PublicList data={data} /></section></>; }

function PaymentSummary({ data }: { data: DashboardData | null }) { return <div className="mb-4 grid gap-4 sm:grid-cols-2">{data ? <><div className="card flex items-center gap-4 p-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-amber-100 text-amber-700"><i className="fa-solid fa-money-bill-wave" /></span><div><p className="text-sm text-slate-500">ยอดรับเป็นเงินสด</p><p className="font-extrabold text-slate-800">{money.format(data.totalCashAmount)}</p></div></div><div className="card flex items-center gap-4 p-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-sky-100 text-sky-700"><i className="fa-solid fa-building-columns" /></span><div><p className="text-sm text-slate-500">ยอดรับเป็นเงินโอน</p><p className="font-extrabold text-slate-800">{money.format(data.totalTransferAmount)}</p></div></div></> : <><div className="skeleton h-20" /><div className="skeleton h-20" /></>}</div>; }
function PublicAdminView({ data, load, backToAdmin }: { data: DashboardData | null; load: () => Promise<void>; backToAdmin: () => void }) { return <div className="public-admin-view"><PublicView data={data} load={load} openLogin={backToAdmin} /></div>; }
function PublicList({ data }: { data: DashboardData | null }) { return <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5 sm:p-6"><div><h2 className="font-extrabold"><i className="fa-solid fa-list-check mr-2 text-orange-500" />รายการแห่ผ้าป่าทั้งหมด</h2><p className="mt-1 text-sm text-slate-500">ข้อมูลอัปเดตจากฝ่ายรับลงทะเบียน</p></div>{data && <span className="rounded-full bg-orange-50 px-3 py-1 text-sm font-bold text-orange-700">{data.totalBatches} รุ่น</span>}</div>{!data ? <LoadingRows /> : data.donations.length === 0 ? <Empty /> : <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-6 py-4">รุ่นที่</th><th className="px-4 py-4">ชื่อรุ่น / กลุ่ม</th><th className="px-4 py-4 text-right">เงินสด</th><th className="px-4 py-4 text-right">เงินโอน</th><th className="px-4 py-4 text-right">รวม</th><th className="px-6 py-4 text-center">วันที่และเวลา</th></tr></thead><tbody>{data.donations.map((d) => <tr className="border-t border-slate-100 hover:bg-orange-50/40" key={d.id}><td className="px-6 py-4 font-bold">{d.batchNumber}</td><td className="px-4 py-4"><p>{d.batchName}</p>{d.note && <p className="text-xs text-slate-400">{d.note}</p>}</td><td className="px-4 py-4 text-right text-slate-600">{money.format(d.cashAmount)}</td><td className="px-4 py-4 text-right text-sky-700">{money.format(d.transferAmount)}</td><td className="px-4 py-4 text-right font-extrabold text-emerald-600">{money.format(d.amount)}</td><td className="px-6 py-4 text-center text-xs text-slate-500">{date.format(new Date(d.receivedAt))}</td></tr>)}</tbody></table></div><div className="divide-y divide-slate-100 md:hidden">{data.donations.map((d) => <MobileRow key={d.id} donation={d} />)}</div></>}</section>; }
function AdminView(props: { data: DashboardData | null; tab: "record" | "stats"; setTab: (x: "record" | "stats") => void; form: DonationInput; update: (k: keyof DonationInput, v: string) => void; save: (e: FormEvent<HTMLFormElement>) => void; editing: Donation | null; clearEditor: () => void; busy: boolean; rows: Donation[]; query: string; setQuery: (x: string) => void; edit: (d: Donation) => void; remove: (d: Donation) => void; logout: () => void; load: () => Promise<void> }) {
  const { data, tab, setTab, form, update, save, editing, clearEditor, busy, rows, query, setQuery, edit, remove, logout, load } = props;
  return <><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6"><Brand admin /><button className="btn bg-slate-800 text-sm text-white hover:bg-slate-700" onClick={() => void logout()}><i className="fa-solid fa-right-from-bracket" />ออกจากระบบ</button></div></header><section className="mx-auto max-w-7xl px-4 py-7 sm:px-6"><div className="mb-6 flex items-center gap-2 rounded-2xl bg-white p-2 shadow-sm"><Tab active={tab === "record"} click={() => setTab("record")} icon="fa-circle-plus" text="บันทึกข้อมูล" /><Tab active={tab === "stats"} click={() => setTab("stats")} icon="fa-chart-pie" text="สถิติและจัดการ" /></div>{tab === "record" ? <DonationForm form={form} update={update} save={save} editing={editing} clearEditor={clearEditor} busy={busy} /> : <><div className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat icon="fa-baht-sign" label="ยอดผ้าป่ารวม" value={data ? money.format(data.totalAmount) : "–"} color="emerald" /><Stat icon="fa-money-bill-wave" label="รับเป็นเงินสด" value={data ? money.format(data.totalCashAmount) : "–"} color="orange" /><Stat icon="fa-building-columns" label="รับเป็นเงินโอน" value={data ? money.format(data.totalTransferAmount) : "–"} color="sky" /><Stat icon="fa-list" label="จำนวนรายการ" value={data ? `${data.totalRecords} รายการ` : "–"} color="sky" /></div><section className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><h2 className="font-extrabold"><i className="fa-solid fa-table-list mr-2 text-orange-500" />จัดการรายการผ้าป่า</h2><div className="flex gap-2"><input className="field w-full py-2 text-sm sm:w-60" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ค้นหารายการ" /><a href="/report" target="_blank" rel="noreferrer" className="btn btn-primary px-3 text-sm"><i className="fa-solid fa-print" /><span className="hidden sm:inline">พิมพ์รายงาน</span></a><button className="btn btn-soft px-3" onClick={() => void load()}><i className="fa-solid fa-rotate-right" /></button></div></div>{!data ? <LoadingRows /> : rows.length === 0 ? <Empty /> : <AdminTable rows={rows} edit={edit} remove={remove} />}</section></>}</section></>;
}

function DonationForm({ form, update, save, editing, clearEditor, busy }: { form: DonationInput; update: (key: keyof DonationInput, value: string) => void; save: (e: FormEvent<HTMLFormElement>) => void; editing: Donation | null; clearEditor: () => void; busy: boolean }) {
  const total = form.cashAmount + form.transferAmount;
  return <form onSubmit={save} className="card mx-auto max-w-3xl p-6 sm:p-8"><div className="mb-7 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-amber-100 text-orange-600"><i className="fa-solid fa-pen-to-square" /></span><div><h1 className="text-xl font-extrabold">{editing ? "แก้ไขรายการผ้าป่า" : "บันทึกยอดผ้าป่า"}</h1><p className="text-sm text-slate-500">แยกเงินสดและเงินโอน ระบบจะรวมยอดให้ก่อนบันทึก</p></div></div><div className="grid gap-5 sm:grid-cols-2"><Field label="รุ่นที่" icon="fa-hashtag"><input className="field" required value={form.batchNumber} onChange={(e) => update("batchNumber", e.target.value)} placeholder="เช่น รุ่น 36" /></Field><Field label="ชื่อรุ่น / กลุ่ม" icon="fa-users"><input className="field" required value={form.batchName} onChange={(e) => update("batchName", e.target.value)} placeholder="ระบุชื่อรุ่น" /></Field><Field label="เงินสด (บาท)" icon="fa-money-bill-wave"><input className="field" type="number" min="0" step="0.01" value={form.cashAmount || ""} onChange={(e) => update("cashAmount", e.target.value)} placeholder="0.00" /></Field><Field label="เงินโอน (บาท)" icon="fa-building-columns"><input className="field" type="number" min="0" step="0.01" value={form.transferAmount || ""} onChange={(e) => update("transferAmount", e.target.value)} placeholder="0.00" /></Field><Field label="หมายเหตุ" icon="fa-note-sticky"><input className="field" value={form.note} onChange={(e) => update("note", e.target.value)} placeholder="ไม่บังคับ" /></Field><div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3"><p className="text-sm font-bold text-emerald-800"><i className="fa-solid fa-calculator mr-2" />ยอดรวมที่จะบันทึก</p><p className="mt-1 text-2xl font-black text-emerald-700">{money.format(total)}</p><p className="mt-1 text-xs text-emerald-700/80">เงินสด {money.format(form.cashAmount)} · เงินโอน {money.format(form.transferAmount)}</p></div></div><div className="mt-7 flex justify-end gap-2">{editing && <button type="button" onClick={clearEditor} className="btn btn-soft">ยกเลิก</button>}<button disabled={busy || total <= 0} className="btn btn-primary"><Busy active={busy} /><i className="fa-solid fa-floppy-disk" />{editing ? "บันทึกการแก้ไข" : "บันทึกรายการ"}</button></div></form>;
}
function AdminTable({ rows, edit, remove }: { rows: Donation[]; edit: (d: Donation) => void; remove: (d: Donation) => void }) { return <div className="overflow-x-auto"><table className="w-full min-w-175 text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-6 py-4">รุ่นที่ / ชื่อรุ่น</th><th className="px-4 py-4 text-right">เงินสด</th><th className="px-4 py-4 text-right">เงินโอน</th><th className="px-4 py-4 text-right">รวม</th><th className="px-4 py-4">วันที่บันทึก</th><th className="px-6 py-4 text-right">จัดการ</th></tr></thead><tbody>{rows.map((d) => <tr className="border-t border-slate-100" key={d.id}><td className="px-6 py-4"><p className="font-bold">{d.batchNumber}</p><p className="text-xs text-slate-500">{d.batchName}{d.note && ` · ${d.note}`}</p></td><td className="px-4 py-4 text-right text-slate-600">{money.format(d.cashAmount)}</td><td className="px-4 py-4 text-right text-sky-700">{money.format(d.transferAmount)}</td><td className="px-4 py-4 text-right font-extrabold text-emerald-600">{money.format(d.amount)}</td><td className="px-4 py-4 text-xs text-slate-500">{date.format(new Date(d.receivedAt))}</td><td className="px-6 py-4 text-right"><button onClick={() => edit(d)} className="mr-1 rounded-lg p-2 text-orange-600 hover:bg-orange-50"><i className="fa-solid fa-pen" /></button><button onClick={() => remove(d)} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50"><i className="fa-solid fa-trash-can" /></button></td></tr>)}</tbody></table></div>; }
function LoginModal({ login, setLogin, close, submit, busy }: { login: { username: string; password: string }; setLogin: (v: { username: string; password: string }) => void; close: () => void; submit: (e: FormEvent<HTMLFormElement>) => void; busy: boolean }) { return <div className="fixed inset-0 z-40 grid place-items-center bg-slate-950/35 p-4"><form onSubmit={submit} className="card w-full max-w-md p-6 shadow-2xl"><div className="flex justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-amber-100 text-orange-600"><i className="fa-solid fa-user-shield" /></span><button type="button" onClick={close} className="p-2 text-slate-400"><i className="fa-solid fa-xmark" /></button></div><h2 className="mt-4 text-lg font-extrabold">เข้าสู่ระบบผู้ดูแล</h2><p className="mt-1 text-sm text-slate-500">สำหรับจัดการยอดผ้าป่า</p><div className="mt-5 space-y-4"><Field label="ชื่อผู้ใช้" icon="fa-user"><input className="field" required autoFocus value={login.username} onChange={(e) => setLogin({ ...login, username: e.target.value })} /></Field><Field label="รหัสผ่าน" icon="fa-key"><input className="field" required type="password" value={login.password} onChange={(e) => setLogin({ ...login, password: e.target.value })} /></Field></div><button disabled={busy} className="btn btn-primary mt-6 w-full"><Busy active={busy} /><i className="fa-solid fa-right-to-bracket" />เข้าสู่ระบบ</button></form></div>; }
function DeleteModal({ donation, cancel, confirm, busy }: { donation: Donation; cancel: () => void; confirm: () => void; busy: boolean }) { return <div className="fixed inset-0 z-40 grid place-items-center bg-slate-950/35 p-4"><div className="card w-full max-w-md p-6 shadow-2xl"><span className="grid h-11 w-11 place-items-center rounded-xl bg-rose-100 text-rose-600"><i className="fa-solid fa-trash-can" /></span><h2 className="mt-4 text-lg font-extrabold">ลบรายการนี้หรือไม่?</h2><p className="mt-2 text-sm text-slate-500">{donation.batchNumber} · {donation.batchName}<br />การลบไม่สามารถย้อนกลับได้</p><div className="mt-6 flex justify-end gap-2"><button className="btn btn-soft" onClick={cancel}>ยกเลิก</button><button disabled={busy} onClick={confirm} className="btn btn-danger"><Busy active={busy} /><i className="fa-solid fa-trash-can" />ลบรายการ</button></div></div></div>; }
function Field({ label, icon, children }: { label: string; icon: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-sm font-bold text-slate-700"><i className={`fa-solid ${icon} mr-2 text-orange-500`} />{label}</span>{children}</label>; }
function Tab({ active, click, icon, text }: { active: boolean; click: () => void; icon: string; text: string }) { return <button onClick={click} className={`flex-1 whitespace-nowrap rounded-full px-5 py-2.5 text-sm font-bold transition sm:flex-none ${active ? "bg-orange-500 text-white shadow-md shadow-orange-200" : "text-slate-500 hover:bg-orange-100/70"}`}><i className={`fa-solid ${icon} mr-2`} />{text}</button>; }
function Stat({ icon, label, value, color }: { icon: string; label: string; value: string; color: "emerald" | "orange" | "sky" }) { const colors = { emerald: "bg-emerald-100 text-emerald-600", orange: "bg-orange-100 text-orange-600", sky: "bg-sky-100 text-sky-600" }; return <div className="card p-5"><span className={`grid h-10 w-10 place-items-center rounded-xl ${colors[color]}`}><i className={`fa-solid ${icon}`} /></span><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-xl font-extrabold">{value}</p></div>; }
function Busy({ active }: { active: boolean }) { return active ? <span className="spinner" /> : null; }
function Empty() { return <div className="p-14 text-center text-slate-500"><i className="fa-regular fa-folder-open mb-3 block text-4xl text-slate-300" />ยังไม่มีข้อมูลผ้าป่า</div>; }
function LoadingRows() { return <div className="space-y-4 p-6">{[1, 2, 3, 4].map((n) => <div className="flex justify-between" key={n}><div className="w-1/2 space-y-2"><div className="skeleton h-4 w-1/3" /><div className="skeleton h-3 w-2/3" /></div><div className="skeleton h-5 w-24" /></div>)}</div>; }
function MobileRow({ donation }: { donation: Donation }) { return <article className="p-5"><div className="flex justify-between gap-3"><div><p className="font-bold">{donation.batchNumber}</p><p className="text-sm text-slate-600">{donation.batchName}</p></div><p className="font-extrabold text-emerald-600">{money.format(donation.amount)}</p></div><p className="mt-2 text-xs text-slate-500">เงินสด {money.format(donation.cashAmount)} · เงินโอน {money.format(donation.transferAmount)}</p><p className="mt-1 text-xs text-slate-500"><i className="fa-regular fa-clock mr-1" />{date.format(new Date(donation.receivedAt))}</p></article>; }
